#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Commands\ConfigGenCommand;

$application = new Application();
$application->add(new ConfigGenCommand());
$application->run();